### ISSUE TITLE
Error while app creation

### ISSUE THREAD

**Issue by sigaev-pro** [DevExpress/devextreme-vue-template#6]
Hello,

I have a problem when creating a new application on a 'build-themes' step.

```
> arbiterm@0.1.0 build-themes /home/vadim/projects/aterm/arbiterm
> devextreme build

The DevExtreme build started
/home/vadim/projects/aterm/arbiterm/node_modules/less/lib/less-node/index.js:1
import environment from './environment';
       ^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.runThemeBuilder [as run] (/home/vadim/projects/aterm/arbiterm/node_modules/devextreme-cli/commands/themebuider.js:127:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! arbiterm@0.1.0 build-themes: `devextreme build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the arbiterm@0.1.0 build-themes script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vadim/.npm/_logs/2019-08-18T10_59_39_892Z-debug.log

```

**Comment by dxvladislavvolkov** [comment]
Fixed in devextreme-cli@1.1.6
